### ISSUE TITLE
Runetime Error When Retrieving

### ISSUE THREAD

**Issue by Tsangares** [iotaledger-archive/mam.client.js#50]
I have the following code:
```
console.log("Initialized")                                                                                                                                                             
function getData(ROOT,payload=[],counter=1){                                                                                                                             
    return Mam.fetchSingle(ROOT,mode,null,null)                                                                                                                          
            .then(response=>{                                                                                                                                            
                msg=parseMsg(response.payload)                                                                                                                           
                if (msg==undefined) return payload                                                                                                                       
                payload.push(msg)                                                                                                                                        
                console.log("recieved",counter)                                                                                                                          
                return getData(response.nextRoot,payload,counter+1)                                                                                                      
            })                                                                                                                                                           
}                                                                                                                                                                        
getData(root)                                                                                                                                                            
    .then(msg=>console.log("SUC",msg))                                                                                                                                   
    .catch(msg=>console.log("FAIL",msg)) 
```
That uses `Mam.fetchSingle` to get a message and if the message is undefined (empty) it stops, otherwise it will try to get the `nextRoot`.  I did this instead of fetch because fetch was also giving me errors.

 The error I receive is at the bottom of this post. From my testing it feels like there is a random chance that this error will show up and the code will stop traversing the mam stream. 

Is this an error with the connection to my iri node?
I am using `https://dyn.tangle-nodes.com` as my provider.
```
wil@taxi ~/D/temperature> node read.js
Initialized
recieved 1
RuntimeError: unreachable
    at __rust_start_panic (wasm-function[27]:1)
    at rust_panic (wasm-function[26]:31)
    at std::panicking::rust_panic_with_hook::ha9514ccd859407a0 (wasm-function[23]:304)
    at std::panicking::continue_panic_fmt::hbdf64f9b91d66da7 (wasm-function[22]:114)
    at rust_begin_unwind (wasm-function[21]:3)
    at core::panicking::panic_fmt::hf7e0ef817f8396d5 (wasm-function[49]:70)
    at core::slice::slice_index_len_fail::ha1c53d14fa8e35d6 (wasm-function[46]:133)
    at iota_pascal::pascal::decode::h5b7fd1e7b571470a (wasm-function[170]:114)
    at iota_mam::mam::parse::h02cbb86a73276d2d (wasm-function[190]:22)
    at iota_mam_parse (wasm-function[194]:108)
    at Object.decodeMessage (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:55470:2353)
    at /home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:55480:1020
    at Array.map (<anonymous>)
    at /home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:55480:961
    at tryCatcher (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51816:585)
    at Promise._settlePromiseFromHandler (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51756:13245)
    at Promise._settlePromise (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51756:14689)
    at Promise._settlePromise0 (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51756:15793)
    at Promise._settlePromises (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51756:17564)
    at _drainQueueStep (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51649:2973)
    at _drainQueue (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51649:2865)
    at Async._drainQueues (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51649:3110)
RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::ha9514ccd859407a0 (wasm-function[23]:297)
    at std::panicking::continue_panic_fmt::hbdf64f9b91d66da7 (wasm-function[22]:114)
    at rust_begin_unwind (wasm-function[21]:3)
    at core::panicking::panic_fmt::hf7e0ef817f8396d5 (wasm-function[49]:70)
    at core::slice::slice_index_len_fail::ha1c53d14fa8e35d6 (wasm-function[46]:133)
    at iota_pascal::pascal::decode::h5b7fd1e7b571470a (wasm-function[170]:114)
    at iota_mam::mam::parse::h02cbb86a73276d2d (wasm-function[190]:22)
    at iota_mam_parse (wasm-function[194]:108)
    at Object.decodeMessage (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:55470:2353)
    at /home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:55480:1020
    at Array.map (<anonymous>)
    at /home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:55480:961
    at tryCatcher (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51816:585)
    at Promise._settlePromiseFromHandler (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51756:13245)
    at Promise._settlePromise (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51756:14689)
    at Promise._settlePromise0 (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51756:15793)
    at Promise._settlePromises (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51756:17564)
    at _drainQueueStep (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51649:2973)
    at _drainQueue (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51649:2865)
    at Async._drainQueues (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51649:3110)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51649:770)
    at processImmediate (timers.js:637:19)
RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::ha9514ccd859407a0 (wasm-function[23]:297)
    at std::panicking::continue_panic_fmt::hbdf64f9b91d66da7 (wasm-function[22]:114)
    at rust_begin_unwind (wasm-function[21]:3)
    at core::panicking::panic_fmt::hf7e0ef817f8396d5 (wasm-function[49]:70)
    at core::slice::slice_index_len_fail::ha1c53d14fa8e35d6 (wasm-function[46]:133)
    at iota_pascal::pascal::decode::h5b7fd1e7b571470a (wasm-function[170]:114)
    at iota_mam::mam::parse::h02cbb86a73276d2d (wasm-function[190]:22)
    at iota_mam_parse (wasm-function[194]:108)
    at Object.decodeMessage (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:55470:2353)
    at /home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:55480:1020
    at Array.map (<anonymous>)
    at /home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:55480:961
    at tryCatcher (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51816:585)
    at Promise._settlePromiseFromHandler (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51756:13245)
    at Promise._settlePromise (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51756:14689)
    at Promise._settlePromise0 (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51756:15793)
    at Promise._settlePromises (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51756:17564)
    at _drainQueueStep (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51649:2973)
    at _drainQueue (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51649:2865)
    at Async._drainQueues (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51649:3110)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/wil/Desktop/temperature/node_modules/@iota/mam/lib/mam.client.js:51649:770)
    at processImmediate (timers.js:637:19)
SUC [ { time: 1552512220.9557037,
    humidity: 19.899999618530273,
    temperature: 24.799999237060547 } ]
wil@taxi ~/D/temperature> 
```

**Comment by obany** [comment]
I have created a mam channel with some messages in it which you can see here
https://thetangle.org/mam/NROYGCVJBDUCATCXRJXD9TEEELDCFWKDNAGNTHMGJUWO9AQMXMYKFWOLETRTHPOYXCIDA9R9PDTVZYHYZ

Also I have created a sandbox with your code in it here 
https://codesandbox.io/s/rw52y1rlom

It is connected to the same node as your example, could you try using the sandbox and see if you are still getting the errors, for me it runs every time without problem.

**Comment by obany** [comment]
No response so closing

**Comment by Tsangares** [comment]
Hi, srry, i did not notice you respond. I would like to continue working on this. 
Note, I was using node.js instead of javascript. In the sandbox above, I have noticing the payload keeps being undefined. 
The response object seems to be an error `captureFrameStrings`
