### ISSUE TITLE
A problem on fetching And i need a fast response please

### ISSUE THREAD

**Issue by yehia67** [iotaledger-archive/mam.client.js#67]
Hello everyone. My graduation project defence is tomorrow and I have to present a prototype type of my work...  2 week ago I let my code to study for my final exams and now I have this error for fetching MAM restricted object. It happens even to the restricted code on their repo https://github.com/iotaledger/mam.client.js/blob/master/example/publishAndFetchRestricted.js
Could anyone please give me a fast solution as I had to present my prototype tomorrow and it isn't working I don't know why? It was working 2 weeks ago and I did not touch the code since then.

Error I get on my project
```
yehia@yehia-Iaptop:~/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules$ node testMam.js 
AAPGUYNRWAZGETXRCMQHKDKP9ODILBVPUZZQFNKCT9ZECOCGHZFNXUZOFPXCACNHZPBNBCYFUKIKGDGGQ
RuntimeError: unreachable
    at __rust_start_panic (wasm-function[27]:1)
    at rust_panic (wasm-function[26]:31)
    at std::panicking::rust_panic_with_hook::ha9514ccd859407a0 (wasm-function[23]:304)
    at std::panicking::continue_panic_fmt::hbdf64f9b91d66da7 (wasm-function[22]:114)
    at rust_begin_unwind (wasm-function[21]:3)
    at core::panicking::panic_fmt::hf7e0ef817f8396d5 (wasm-function[49]:70)
    at core::slice::slice_index_len_fail::ha1c53d14fa8e35d6 (wasm-function[46]:133)
    at iota_pascal::pascal::decode::h5b7fd1e7b571470a (wasm-function[170]:114)
    at iota_mam::mam::parse::h02cbb86a73276d2d (wasm-function[190]:22)
    at iota_mam_parse (wasm-function[194]:108)
    at Object.decodeMessage (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:6722:2353)
    at /home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:6732:1020
    at Array.map (<anonymous>)
    at /home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:6732:961
    at tryCatcher (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:3068:587)
    at Promise._settlePromiseFromHandler (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:3008:13247)
    at Promise._settlePromise (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:3008:14689)
    at Promise._settlePromise0 (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:3008:15793)
    at Promise._settlePromises (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:3008:17564)
    at _drainQueueStep (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:2901:2975)
    at _drainQueue (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:2901:2867)
    at Async._drainQueues (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:2901:3112)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:2901:772)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::ha9514ccd859407a0 (wasm-function[23]:297)
    at std::panicking::continue_panic_fmt::hbdf64f9b91d66da7 (wasm-function[22]:114)
    at rust_begin_unwind (wasm-function[21]:3)
    at core::panicking::panic_fmt::hf7e0ef817f8396d5 (wasm-function[49]:70)
    at core::slice::slice_index_len_fail::ha1c53d14fa8e35d6 (wasm-function[46]:133)
    at iota_pascal::pascal::decode::h5b7fd1e7b571470a (wasm-function[170]:114)
    at iota_mam::mam::parse::h02cbb86a73276d2d (wasm-function[190]:22)
    at iota_mam_parse (wasm-function[194]:108)
    at Object.decodeMessage (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:6722:2353)
    at /home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:6732:1020
    at Array.map (<anonymous>)
    at /home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:6732:961
    at tryCatcher (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:3068:587)
    at Promise._settlePromiseFromHandler (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:3008:13247)
    at Promise._settlePromise (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:3008:14689)
    at Promise._settlePromise0 (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:3008:15793)
    at Promise._settlePromises (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:3008:17564)
    at _drainQueueStep (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:2901:2975)
    at _drainQueue (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:2901:2867)
    at Async._drainQueues (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:2901:3112)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:2901:772)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::ha9514ccd859407a0 (wasm-function[23]:297)
    at std::panicking::continue_panic_fmt::hbdf64f9b91d66da7 (wasm-function[22]:114)
    at rust_begin_unwind (wasm-function[21]:3)
    at core::panicking::panic_fmt::hf7e0ef817f8396d5 (wasm-function[49]:70)
    at core::slice::slice_index_len_fail::ha1c53d14fa8e35d6 (wasm-function[46]:133)
    at iota_pascal::pascal::decode::h5b7fd1e7b571470a (wasm-function[170]:114)
    at iota_mam::mam::parse::h02cbb86a73276d2d (wasm-function[190]:22)
    at iota_mam_parse (wasm-function[194]:108)
    at Object.decodeMessage (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:6722:2353)
    at /home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:6732:1020
    at Array.map (<anonymous>)
    at /home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:6732:961
    at tryCatcher (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:3068:587)
    at Promise._settlePromiseFromHandler (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:3008:13247)
    at Promise._settlePromise (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:3008:14689)
    at Promise._settlePromise0 (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:3008:15793)
    at Promise._settlePromises (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:3008:17564)
    at _drainQueueStep (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:2901:2975)
    at _drainQueue (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:2901:2867)
    at Async._drainQueues (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:2901:3112)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/yehia/Documents/graduationProject/prototypes/Recycler-api/api/controllers/iota_comm_modules/node_modules/@iota/mam/lib/mam.client.js:2901:772)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)

```

Error when I run your restricted example:

```Published { message: 'Message from Alice',
  timestamp: '1/22/2020, 8:33:02 PM' } 

Published { message: 'Message from Bob',
  timestamp: '1/22/2020, 8:33:04 PM' } 

Published { message: 'Message from Charlie',
  timestamp: '1/22/2020, 8:33:07 PM' } 

Fetched and parsed { message: 'Message from Alice',
  timestamp: '1/22/2020, 8:33:02 PM' } 

Fetched and parsed { message: 'Message from Bob',
  timestamp: '1/22/2020, 8:33:04 PM' } 

RuntimeError: unreachable
    at __rust_start_panic (wasm-function[27]:1)
    at rust_panic (wasm-function[26]:31)
    at std::panicking::rust_panic_with_hook::ha9514ccd859407a0 (wasm-function[23]:304)
    at std::panicking::continue_panic_fmt::hbdf64f9b91d66da7 (wasm-function[22]:114)
    at rust_begin_unwind (wasm-function[21]:3)
    at core::panicking::panic_fmt::hf7e0ef817f8396d5 (wasm-function[49]:70)
    at core::slice::slice_index_len_fail::ha1c53d14fa8e35d6 (wasm-function[46]:133)
    at iota_pascal::pascal::decode::h5b7fd1e7b571470a (wasm-function[170]:114)
    at iota_mam::mam::parse::h02cbb86a73276d2d (wasm-function[190]:22)
    at iota_mam_parse (wasm-function[194]:108)
    at Object.decodeMessage (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:6722:2353)
    at /home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:6732:1020
    at Array.map (<anonymous>)
    at /home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:6732:961
    at tryCatcher (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:3068:587)
    at Promise._settlePromiseFromHandler (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:3008:13247)
    at Promise._settlePromise (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:3008:14689)
    at Promise._settlePromise0 (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:3008:15793)
    at Promise._settlePromises (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:3008:17564)
    at _drainQueueStep (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:2901:2975)
    at _drainQueue (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:2901:2867)
    at Async._drainQueues (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:2901:3112)
RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::ha9514ccd859407a0 (wasm-function[23]:297)
    at std::panicking::continue_panic_fmt::hbdf64f9b91d66da7 (wasm-function[22]:114)
    at rust_begin_unwind (wasm-function[21]:3)
    at core::panicking::panic_fmt::hf7e0ef817f8396d5 (wasm-function[49]:70)
    at core::slice::slice_index_len_fail::ha1c53d14fa8e35d6 (wasm-function[46]:133)
    at iota_pascal::pascal::decode::h5b7fd1e7b571470a (wasm-function[170]:114)
    at iota_mam::mam::parse::h02cbb86a73276d2d (wasm-function[190]:22)
    at iota_mam_parse (wasm-function[194]:108)
    at Object.decodeMessage (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:6722:2353)
    at /home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:6732:1020
    at Array.map (<anonymous>)
    at /home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:6732:961
    at tryCatcher (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:3068:587)
    at Promise._settlePromiseFromHandler (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:3008:13247)
    at Promise._settlePromise (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:3008:14689)
    at Promise._settlePromise0 (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:3008:15793)
    at Promise._settlePromises (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:3008:17564)
    at _drainQueueStep (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:2901:2975)
    at _drainQueue (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:2901:2867)
    at Async._drainQueues (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:2901:3112)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:2901:772)
    at runCallback (timers.js:705:18)
RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::ha9514ccd859407a0 (wasm-function[23]:297)
    at std::panicking::continue_panic_fmt::hbdf64f9b91d66da7 (wasm-function[22]:114)
    at rust_begin_unwind (wasm-function[21]:3)
    at core::panicking::panic_fmt::hf7e0ef817f8396d5 (wasm-function[49]:70)
    at core::slice::slice_index_len_fail::ha1c53d14fa8e35d6 (wasm-function[46]:133)
    at iota_pascal::pascal::decode::h5b7fd1e7b571470a (wasm-function[170]:114)
    at iota_mam::mam::parse::h02cbb86a73276d2d (wasm-function[190]:22)
    at iota_mam_parse (wasm-function[194]:108)
    at Object.decodeMessage (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:6722:2353)
    at /home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:6732:1020
    at Array.map (<anonymous>)
    at /home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:6732:961
    at tryCatcher (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:3068:587)
    at Promise._settlePromiseFromHandler (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:3008:13247)
    at Promise._settlePromise (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:3008:14689)
    at Promise._settlePromise0 (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:3008:15793)
    at Promise._settlePromises (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:3008:17564)
    at _drainQueueStep (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:2901:2975)
    at _drainQueue (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:2901:2867)
    at Async._drainQueues (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:2901:3112)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/yehia/Documents/graduationProject/prototypes/Tangle&IPFS Database/node_modules/@iota/mam/lib/mam.client.js:2901:772)
    at runCallback (timers.js:705:18)
Fetched and parsed { message: 'Message from Alice',
  timestamp: '1/22/2020, 8:33:02 PM' } 

Verify with MAM Explorer:
https://mam-explorer.firebaseapp.com/?provider=https%3A%2F%2Fnodes.devnet.iota.org&mode=restricted&key=VERYSECRETKEY99999999999999999999999999999999999999999999999999999999999999999999&root=NFGFFBPEFRDLGRUVTDNVHDFDLMIYLUUSSZIATGGMAQHZXOVAFVLUPESA9DZHFGJKTNOVUFQGRZHAOTNPH

```
I will appreciate your fast response thanks.

**Comment by kwek20** [comment]
@yehia67 Hey man!

I havent figured out the cause of t his yet, but if  you connect to a mainnet node and change the MWM to lets say 14, the code executes successfully.

Does that help you on the short term? Good luck with your defence!

(I tested it on https://we-did-it.org:14265)

**Comment by yehia67** [comment]
Yes it help thank you.
