### ISSUE TITLE
memory error in the mam module

### ISSUE THREAD

**Issue by ofaessler** [iotaledger-archive/mam.client.js#8]
When running a stream for some time a memory related error occures. I used [rckey ](https://github.com/rckey) SensorNode and -Hub.
```
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 
1527609983963 ERROR (abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at jsStackTrace (/home/of/myapps/SensorNode/node_modules/mam.node.js/mam.node.js:9210:18008)
    at stackTrace (/home/of/myapps/SensorNode/node_modules/mam.node.js/mam.node.js:9210:18179)
    at abort (/home/of/myapps/SensorNode/node_modules/mam.node.js/mam.node.js:9223:17022)
    at abortOnCannotGrowMemory (/home/of/myapps/SensorNode/node_modules/mam.node.js/mam.node.js:9210:19053)
    at enlargeMemory (/home/of/myapps/SensorNode/node_modules/mam.node.js/mam.node.js:9210:19512)
    at Ml (/home/of/myapps/SensorNode/node_modules/mam.node.js/mam.node.js:9216:75543)
    at Ik (/home/of/myapps/SensorNode/node_modules/mam.node.js/mam.node.js:9216:49875)
    at Lk (/home/of/myapps/SensorNode/node_modules/mam.node.js/mam.node.js:9216:59013)
    at Pd (/home/of/myapps/SensorNode/node_modules/mam.node.js/mam.node.js:9215:59593)
    at wb (/home/of/myapps/SensorNode/node_modules/mam.node.js/mam.node.js:9215:451)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.)
```

https://github.com/rckey/SensorNode
https://github.com/rckey/SensorHub

**Comment by obany** [comment]
This is now very old and the library has changed considerably since then, we can probably close this issue.
